version: '3.4'

services:
  doctors.api:
    image: ${DOCKER_REGISTRY-}doctorsapi
    build:
      context: ../Services
      dockerfile: Doctors/Doctors.API/Dockerfile
    depends_on: 
     - sqlServer
     - rabbitMQ

  clinics.api:
    image: ${DOCKER_REGISTRY-}clinicsapi
    build:
      context: ../Services
      dockerfile: Clinics/Clinics.API/Dockerfile
    depends_on:
    - sqlServer
    - rabbitMQ

  timetable.api:
    image: ${DOCKER_REGISTRY-}timetableapi
    build:
      context: ../Services
      dockerfile: Timetable/Timetable.API/Dockerfile
    depends_on:
    - sqlServer
    - rabbitMQ
 
  sqlServer:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlServer
    environment:
     - MSSQL_SA_PASSWORD=P@ssword1
     - ACCEPT_EULA=Y
    ports:
     - 1435:1433

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitMq
    ports:
    - 5672:5672
    - 15672:15672

  micromed.gateway:
    image: ${DOCKER_REGISTRY-}micromedgateway
    build:
      context: ..
      dockerfile: Gateway/MicroMed.Gateway/Dockerfile
    depends_on:
    - doctors.api
    - clinics.api
    - timetable.api
